blog/DjangoExtSystem1/DjangoExtSystem/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import static

from DjangoExtSystem import settings
from utils.upload_image import upload_image

from front import views
urlpatterns = [
    path(r'app/', include(('app.urls', 'app'), namespace='app')),
    path('', views.index),
    path(r'users/', include(('users.urls', 'users'), namespace='users')),
    path(r'front/', include(('front.urls', 'front'), namespace='front')),
    # kindeditor编辑器上传图片地址
    re_path(r'^util/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
]

# 配置media访问路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/DjangoExtSystem1/app/urls.py
from django.urls import path

from app import views

urlpatterns = [
    path(r'index/', views.index, name='index'),
]

blog/DjangoExtSystem1/front/urls.py
from django.urls import path
from front import views

urlpatterns = [
    path('index/',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('infopic/<int:id>/',views.infopic,name='infopic'),
    path('list/',views.list,name='list'),
]

blog/DjangoExtSystem1/users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    # 注册
    path('register/', views.register, name='register'),
    # 登录
    path('login/', views.login, name='login'),
    # 首页
    path('index/', views.index, name='index'),
    # 注销
    path('logout/', views.logout, name='logout'),
    # 编辑文章
    path('edit_article/<int:id>/', views.edit_article, name='edit_article'),
    # 文章列表
    path('article/', views.article, name='article'),
    path('category/', views.category, name='category'),
    path('add_article/', views.add_article, name='add_article'),
    path('del_article/<int:id>/', views.del_article, name='del_article'),
    path('add_category/', views.add_category, name='add_category'),
    path('del_category/<int:id>/', views.del_category, name='del_category'),
    path('edit_category/<int:id>/', views.edit_category, name='edit_category'),
    path('add_resueme/',views.add_resueme,name='add_resueme')
]

blog/DjangoExtSystem1/templates/article.html
{% extends 'base_main.html' %}

{% block title %}
文章 --- 异清轩博客管理系统
{% endblock %}

{% block content %}
<section class="container-fluid">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">YlsatCMS</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">消息 <span class="badge">1</span></a></li>
            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">admin <span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="{% url 'users:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a data-toggle="modal" data-target="#WeChat">帮助</a></li>
          </ul>
          <form action="" method="post" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li><a href=""></a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'users:index' %}">首页</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li class="active"><a href="{% url 'users:article' %}">文章</a></li>
    </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'users:category' %}">栏目</a></li>
      </ul>
    </aside>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <form action="/Article/checkAll" method="post" >
        <h1 class="page-header">操作</h1>
        <ol class="breadcrumb">
          <li><a href="{% url 'users:add_article' %}">增加文章</a></li>
        </ol>
        <h1 class="page-header">管理 <span class="badge">{{ result3 | length }}</span></h1>
        <div class="table-re
        sponsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>

                <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">序号</span></th>
                <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">标题</span></th>
                <th><span class="glyphicon glyphicon-list"></span> <span class="visible-lg">栏目</span></th>
                <th><span class="glyphicon glyphicon-list"></span> <span class="visible-lg">关键字</span></th>
                <!--<th > <span class="glyphicon glyphicon-list"></span><span class="visible-lg">内容</span></th>-->
                <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">日期</span></th>
                <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
                <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
              </tr>
            </thead>
            <tbody>
            {% for result in result3 %}
                <tr>
                    <td class="hidden-sm">{{ forloop.counter }}</td>
                    <td class="hidden-sm">{{ result.0 }}</td>
                    <td class="hidden-sm">{{ result.1 }}</td>
                    <td class="hidden-sm">{{ result.2 }}</td>
                    <!--<td class="hidden-sm">{{ result.4 }}</td>-->
                    <td class="hidden-sm">{{ result.4 }}</td>
                    <td><a href="{% url 'users:edit_article' result.5 %}">修改</a></td>
                    <td><a href="{% url 'users:del_article'  result.5 %}">删除</a></td>
                </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <footer class="message_footer">
          <nav>
            <li style="size:20px;">当前{{ result3.number }}页，共{{ result3.paginator.num_pages }}页</li>
            <ul class="pagination pagenav">
                {% if result3.has_previous %}
              <li class="disabled"><a href="{% url 'users:article' %}?page={{ result3.previous_page_number }}">上一页</a> </li>
                {% endif %}
              {% for i in result3.paginator.page_range %}
              <li class="active"><a href="{% url 'users:article' %}?page={{ i }}">{{ i }}</a></li>
              {% endfor %}
              {% if result3.has_next %}
              <li><a href="{% url 'users:article' %}?page={{ result3.next_page_number }}">下一页</a> </li>
              {% endif %}
            </ul>
          </nav>
        </footer>
      </form>
    </div>
  </div>
</section>
<!--个人信息模态框-->
<div class="modal fade" id="seeUserInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <form action="" method="post">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" >个人信息</h4>
        </div>
        <div class="modal-body">
          <table class="table" style="margin-bottom:0px;">
            <thead>
              <tr> </tr>
            </thead>
            <tbody>
              <tr>
                <td wdith="20%">姓名:</td>
                <td width="80%"><input type="text" value="王雨" class="form-control" name="truename" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">用户名:</td>
                <td width="80%"><input type="text" value="admin" class="form-control" name="username" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">电话:</td>
                <td width="80%"><input type="text" value="18538078281" class="form-control" name="usertel" maxlength="13" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">旧密码:</td>
                <td width="80%"><input type="password" class="form-control" name="old_password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">新密码:</td>
                <td width="80%"><input type="password" class="form-control" name="password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">确认密码:</td>
                <td width="80%"><input type="password" class="form-control" name="new_password" maxlength="18" autocomplete="off" /></td>
              </tr>
            </tbody>
            <tfoot>
              <tr></tr>
            </tfoot>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
          <button type="submit" class="btn btn-primary">提交</button>
        </div>
      </div>
    </form>
  </div>
</div>
<!--个人登录记录模态框-->
<div class="modal fade" id="seeUserLoginlog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" >登录记录</h4>
      </div>
      <div class="modal-body">
        <table class="table" style="margin-bottom:0px;">
          <thead>
            <tr>
              <th>登录IP</th>
              <th>登录时间</th>
              <th>状态</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>::1:55570</td>
              <td>2016-01-08 15:50:28</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64377</td>
              <td>2016-01-08 10:27:44</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64027</td>
              <td>2016-01-08 10:19:25</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:57081</td>
              <td>2016-01-06 10:35:12</td>
              <td>成功</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--微信二维码模态框-->
<div class="modal fade user-select" id="WeChat" tabindex="-1" role="dialog" aria-labelledby="WeChatModalLabel">
  <div class="modal-dialog" role="document" style="margin-top:120px;max-width:280px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="WeChatModalLabel" style="cursor:default;">微信扫一扫</h4>
      </div>
      <div class="modal-body" style="text-align:center"> <img src="images/weixin.jpg" alt="" style="cursor:pointer"/> </div>
    </div>
  </div>
</div>
<!--提示模态框-->
<div class="modal fade user-select" id="areDeveloping" tabindex="-1" role="dialog" aria-labelledby="areDevelopingModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="areDevelopingModalLabel" style="cursor:default;">该功能正在日以继夜的开发中…</h4>
      </div>
      <div class="modal-body"> <img src="images/baoman/baoman_01.gif" alt="深思熟虑" />
        <p style="padding:15px 15px 15px 100px; position:absolute; top:15px; cursor:default;">很抱歉，程序猿正在日以继夜的开发此功能，本程序将会在以后的版本中持续完善！</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--右键菜单列表-->
<script src="js/bootstrap.min.js"></script>
<script src="js/admin-scripts.js"></script>
<script>
//是否确认删除
$(function(){
	$("#main table tbody tr td a").click(function(){
		var name = $(this);
		var id = name.attr("rel"); //对应id
		if (event.srcElement.outerText == "删除")
		{
			if(window.confirm("此操作不可逆，是否确认？"))
			{
				$.ajax({
					type: "POST",
					url: "/Article/delete",
					data: "id=" + id,
					cache: false, //不缓存此页面
					success: function (data) {
						window.location.reload();
					}
				});
			};
		};
	});
});
    {% endblock %}

blog/DjangoExtSystem1/templates/base_main.html
{% extends 'base.html' %}

    {% block css %}
        <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="/static/css/style.css">
        <link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
        <link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
        <link rel="shortcut icon" href="/static/images/icon/favicon.ico">
        <link rel="stylesheet" type="text/css" href="/static/css/login.css">
    {% endblock %}


    {% block js %}
        <script src="/static/js/jquery-2.1.4.min.js"></script>
    {% endblock %}

blog/DjangoExtSystem1/templates/category.html
{% extends 'base_main.html' %}

    {% block head %}
        <meta charset="utf-8">
        <meta name="renderer" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>栏目 - 异清轩博客管理系统</title>
    {% endblock %}


    {% block content %}
<section class="container-fluid">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">YlsatCMS</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">消息 <span class="badge">1</span></a></li>
            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">admin <span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="{% url 'users:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a data-toggle="modal" data-target="#WeChat">帮助</a></li>
          </ul>
          <form action="" method="post" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li><a href="index.html"></a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'users:index' %}">首页</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'users:article' %}">文章</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li class="active"><a href="{% url 'users:category' %}">栏目</a></li>
      </ul>
    </aside>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        <div class="col-md-5">
          <h1 class="page-header">添加</h1>
          <form action="{% url 'users:add_category' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="form-group">
              <label for="category-name">栏目名称</label>
              <input type="text" id="category-name" name="name" class="form-control" placeholder="在此处输入栏目名称" required autocomplete="off">
              <span class="prompt-text">这将是它在站点上显示的名字。</span> </div>
            <div class="form-group">
              <label for="category-alias">栏目别名</label>
              <input type="text" id="category-alias" name="alias" class="form-control" placeholder="在此处输入栏目别名" required autocomplete="off">
              <span class="prompt-text">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span> </div>
            <div class="form-group">
              <label for="category-fname">父节点</label>
              <select id="category-fname" class="form-control" name="fid">
                <option value="0" selected>无</option>
                {% for result in results %}
                <option value="{{ result.0 }}">{{ result.1 }}</option>
                {% endfor %}
              </select>
              <span class="prompt-text">栏目是有层级关系的，您可以有一个“音乐”分类目录，在这个目录下可以有叫做“流行”和“古典”的子目录。</span> </div>

            <div class="form-group">
              <label for="category-keywords">关键字</label>
              <input type="text" id="category-keywords" name="keywords" class="form-control" placeholder="在此处输入栏目关键字" autocomplete="off">
              <span class="prompt-text">关键字会出现在网页的keywords属性中。</span> </div>

            <div class="form-group">
              <label for="category-describe">描述</label>
              <textarea class="form-control" id="category-describe" name="describe" rows="4" autocomplete="off"></textarea>
              <span class="prompt-text">描述会出现在网页的description属性中。</span> </div>

            <button class="btn btn-primary" type="submit" name="submit">添加新栏目</button>
          </form>
        </div>
        <div class="col-md-7">
          <h1 class="page-header">管理 <span class="badge">3</span></h1>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th><span class="glyphicon glyphicon-paperclip"></span> <span class="visible-lg">ID</span></th>
                  <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">名称</span></th>
                  <th><span class="glyphicon glyphicon-list-alt"></span> <span class="visible-lg">别名</span></th>
                  <th><span class="glyphicon glyphicon-pushpin"></span> <span class="visible-lg">总数</span></th>
                  <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
                </tr>
              </thead>
              <tbody>
              {% for result in results %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ result.0 }}</td>
                  <td>{{ result.1 }}</td>
                  <td>{{ result.2 }}</td>
                  <td>
                    <a href="{% url 'users:edit_category' result.3 %}" rel="1">修改</a>
                    <a href="{% url 'users:del_category' result.3 %}" rel="1">删除</a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            <span class="prompt-text"><strong>注：</strong>删除一个栏目也会删除栏目下的文章和子栏目,请谨慎删除!</span> </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script src="js/bootstrap.min.js"></script>
<script src="js/admin-scripts.js"></script>
<script>
//是否确认删除
$(function(){
	$("#main table tbody tr td a").click(function(){
		var name = $(this);
		var id = name.attr("rel"); //对应id
		if (event.srcElement.outerText === "删除")
		{
			if(window.confirm("此操作不可逆，是否确认？"))
			{
				$.ajax({
					type: "POST",
					url: "/Category/delete",
					data: "id=" + id,
					cache: false, //不缓存此页面
					success: function (data) {
						window.location.reload();
					}
				});
			};
		};
	});
});
</script>
    {% endblock %}

blog/DjangoExtSystem1/templates/index.html
{% extends 'base_main.html' %}

{% block title %}
异清轩博客管理系统
{% endblock %}




  {% block content %}
<section class="container-fluid">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">YlsatCMS</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">消息 <span class="badge">无</span></a></li>
            <li class="dropdown"> <a href="{% url 'users:add_resueme' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">个人信息<span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="{% url 'users:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a href="{% url 'front:index' %}" data-toggle="modal" data-target="#WeChat">返回前端文章</a></li>
          </ul>
          <form action="" method="" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="暂不开放" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="button">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>

  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="index.html"></a></li>

      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'users:index'  %}">首页</a></li></ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'users:article'  %}">文章</a></li></ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'users:category'  %}">栏目</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href=""></a></li>
      </ul>
    </aside>


      <h1 class="page-header"> </h1>
      <h1 class="page-header">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp;&emsp;&emsp;欢迎登陆首页</h1>
    <h1 class="page-header"> </h1>
      <h1 class="page-header">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;系统信息</h1>
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead>
            <tr> </tr>
          </thead>
          <tbody>
            <tr>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;管理员:</td>
              <td>&emsp;&emsp;杨欣楷</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;服务器软件:</td>
              <td>&emsp;&emsp;Apache/2.4.10 (Win32) OpenSSL/1.0.1i mod_fcgid/2.3.9</td>
            </tr>
            <tr>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;浏览器:</td>
              <td>&emsp;&emsp;Chrome47</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;PHP版本:</td>
              <td>&emsp;&emsp;5.6.1</td>
            </tr>
            <tr>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;操作系统:</td>
              <td>&emsp;&emsp;Windows 10</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;PHP运行方式:</td>
              <td>&emsp;&emsp;CGI-FCGI</td>
            </tr>
            <tr>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;登录者IP:</td>
              <td>&emsp;&emsp;::1:55570</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;MYSQL版本:</td>
              <td>&emsp;&emsp;5.5.40</td>
            </tr>
            <tr>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;程序版本:</td>
              <td class="version">&emsp;&emsp;YlsatCMS 1.0 <font size="-6" color="#BBB">(20160108160215)</font></td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;上传文件:</td>
              <td>&emsp;&emsp;可以 <font size="-6" color="#BBB">(最大文件：2M ，表单：8M )</font></td>
            </tr>
            <tr>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;程序编码:</td>
              <td>&emsp;&emsp;UTF-8</td>
              <td>&emsp;&emsp;&emsp;&emsp;当前时间:</td>
              <td id="time1" style="color: black;"></td>
                <script>
                    function mytime(){
                        var a = new Date();
                        var b = a.toLocaleTimeString();
                        var c = a.toLocaleDateString();
                        document.getElementById("time1").innerHTML = c+"&nbsp"+b;
                        }
                    setInterval(function() {mytime()},1000);
                </script>

            </tr>
          </tbody>
          <tfoot>
            <tr></tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</section>

    {% endblock %}