blog/fresh_shop/cart/urls.py
from django.urls import path

from cart import views

urlpatterns = [
    # 加入购物车
    path('add_cart/', views.add_cart, name='add_cart'),
    # 购物车数量的刷新
    path('cart_num/', views.cart_num, name='cart_num'),
    # 购物车
    path('cart/', views.cart, name='cart'),
    # 购物车计算价格
    path('cart_price/', views.cart_price, name='cart_price'),
    # 修改购物车中的数量/选择状态
    path('change_cart/', views.change_cart, name='change_cart'),
    # 删除商品
    path('del_cart/<int:id>/', views.del_cart, name='del_cart'),
]

blog/fresh_shop/fresh_shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import static

from fresh_shop.settings import MEDIA_URL, MEDIA_ROOT, STATICFILES_DIRS

from goods import views
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    # 导入应用
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('goods/', include(('goods.urls', 'goods'), namespace='goods')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    # 首页路径
    path('', views.index),
	re_path(r'^static/(?P<path>.*)$', serve, {"document_root": STATICFILES_DIRS[0]}),
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]

# 配置解析media文件的信息
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

blog/fresh_shop/goods/urls.py
from django.urls import path

from goods import views


urlpatterns = [
    # 首页
    path('index/', views.index, name='index'),
    # 商品详情
    path('detail/<int:id>/', views.detail, name='detail'),
    # 查看更多
    path('list/<int:id>/', views.list, name='list'),
    # 搜索
    path('search/', views.search, name='search'),
]

blog/fresh_shop/order/urls.py
from django.urls import path

from order import views
urlpatterns = [
    # 结算功能
    path('place_order/', views.place_order, name='place_order'),
    # 创建订单
    path('order/', views.order, name='order'),
    # 全部订单
    path('user_order/', views.user_order, name='user_order'),
]

blog/fresh_shop/user/urls.py
from django.urls import path

from user import views

urlpatterns = [
    # 注册
    path('register/', views.register, name='register'),
    # 登录
    path('login/', views.login, name='login'),
    # 退出
    path('logout/', views.logout, name='logout'),
    # 收货地址
    path('user_site/', views.user_site, name='user_site'),
    # 个人信息
    path('user_info/', views.user_info, name='user_info'),
]

blog/fresh_shop/cart/models.py
from django.db import models


# 购物车模型：
from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

blog/fresh_shop/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render

from cart.models import ShoppingCart
from goods.models import Goods


def add_cart(request):
    if request.method == 'POST':
        # 接收商品id值和商品数量
        # 组装存储的商品格式：[goods_id, num, is_select]
        # 组装多个商品格式：[[goods_id, num, is_select],goods_id, num, is_select]
        goods_id = int(request.POST.get('goods_id'))
        goods_num = int(request.POST.get('goods_num'))
        goods_list = [goods_id, goods_num, 1]

        session_goods = request.session.get('goods')
        if session_goods:
            # 1. 添加重复的商品，则修改
            flag = True
            for se_goods in session_goods:
                if se_goods[0] == goods_id:
                    se_goods[1] += goods_num
                    flag = False
            if flag:
                # 2. 添加的商品不存在于购物车中，则新增
                session_goods.append(goods_list)
            request.session['goods'] = session_goods
            count = len(session_goods)
        else:
            # 第一次添加购物车
            # 需组装购物车中商品格式为[[goods_id, num, is_select]]
            request.session['goods'] = [goods_list]
            count = 1
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def cart_num(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        count = len(session_goods) if session_goods else 0
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def cart(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        result = []
        if session_goods:
            # 组装返回格式：[objects1, objects2...]
            # objects===>[Goods Object, num, is_select, total_price]
            for se_goods in session_goods:
                # se_goods为[goods_id, num, is_select]
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                total_price = goods.shop_price * se_goods[1]
                data = [goods, se_goods[1], se_goods[2], total_price]
                result.append(data)
        return render(request, 'cart.html', {'result': result})


def cart_price(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        # 总的商品件数
        all_total = len(session_goods) if session_goods else 0
        all_price = 0
        is_select_num = 0
        for se_goods in session_goods:
            # se_goods为[goods_id, num, is_select]
            if se_goods[2]:
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                all_price += goods.shop_price * se_goods[1]
                is_select_num += 1
        return JsonResponse({'code': 200,
                             'msg': '请求成功',
                             'all_total': all_total,
                             'all_price': all_price,
                             'is_select_num': is_select_num
                             })


def change_cart(request):
    if request.method == 'POST':
        # 修改商品的数量和选择状态
        # 其实就是修改session中商品信息，结构为[goods_id, num, is_select]
        # 1. 获取商品id值和(数量或选择状态)
        goods_id = int(request.POST.get('goods_id'))
        goods_num = request.POST.get('goods_num')
        goods_select = request.POST.get('goods_select')
        # 2. 修改
        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            if se_goods[0] == goods_id:
                se_goods[1] = int(goods_num) if goods_num else se_goods[1]
                se_goods[2] = int(goods_select) if goods_select else se_goods[2]
        request.session['goods'] = session_goods
        return JsonResponse({'code': 200, 'msg': '请求成功'})


def del_cart(request, id):
    if request.method == 'POST':
        # 思路：通过传入的商品id的值，去session中查找，查找到删除数据
        # goods_id = int(request.POST.get('goods_id'))
        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            # se_goods为[goods_id, num, is_select]
            if id == se_goods[0]:
                session_goods.remove(se_goods)
                break
        request.session['goods'] = session_goods
        # 删除数据库中购物车中的商品信息
        user_id = request.session.get('user_id')
        if user_id:
            ShoppingCart.objects.filter(goods_id=id).delete()
        return JsonResponse({'code': 200, 'msg': '请求成功'})

blog/fresh_shop/templates/base_main.html
{% extends 'base.html' %}

{% block css %}
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
{% endblock %}

{% block js1 %}
    {% load static %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% endblock %}

{% block header %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl" {% if user.id %} style="display:block;" {% endif %}>
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
				<div class="login_btn fl"{% if user.id %} style="display:none;" {% endif %}>
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'order:user_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block search %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
            <form action="{% url 'goods:search' %}" method="get">
                {% csrf_token %}
			    <input type="text" class="input_text fl" name="search_goods" placeholder="关键字搜索商品哦">
			    <input type="submit" class="input_btn fr" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
        <script>
            $.get('/cart/cart_num/', function(data){
                if(data.code == '200'){
                    $('#show_count').text(data.count)
                }
            })
        </script>
	</div>
{% endblock %}

{% block footer %}
    <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock %}

blog/fresh_shop/templates/base_user.html
<ul>
    <li><a href="{% url 'user:user_info' %}"
           {% if activate == 'info' %}class="active"{% endif %}
        >· 个人信息</a></li>
    <li><a href="{% url 'order:user_order' %}"
           {% if activate == 'order' %}class="active"{% endif %}
    >· 全部订单</a></li>
    <li><a href="{% url 'user:user_site' %}"
           {% if activate == 'site' %}class="active"{% endif %}
    >· 收货地址</a></li>
</ul>

blog/fresh_shop/templates/detail.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜-商品详情
{% endblock %}


{% block content %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="{% url 'goods:list' 1 %}" class="fruit">新鲜水果</a></li>
					<li><a href="{% url 'goods:list' 2 %}" class="seafood">海鲜水产</a></li>
					<li><a href="{% url 'goods:list' 3 %}" class="meet">猪牛羊肉</a></li>
					<li><a href="{% url 'goods:list' 4 %}" class="egg">禽类蛋品</a></li>
					<li><a href="{% url 'goods:list' 5 %}" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="{% url 'goods:list' 6 %}" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' goods.category_id %}">
            {% for type in category_type %}
                {% if type.0 == goods.category_id %}
                        {{ type.1 }}
                {% endif %}
            {% endfor %}
		</a>
		<span>></span>
		<a href="">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/media/{{ data }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.name }}</h3>
			<p>{{ goods.goods_brief }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="ddf1">{{ goods.shop_price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr" onclick="add_goods();">+</a>
					<a href="javascript:;" class="minus fr" onclick="sub_goods();">-</a>
				</div>
                <script>
                <!--加商品-->
                function add_goods(){
                    var num = $('.num_show').val()
                    var new_num = parseInt(num) + 1
                    $('.num_show').val(new_num)
                    var price = $('#ddf1').text()
                    var new_total = new_num * price
                    $('.total em').text(new_total+'元')
                }
                <!--减商品-->
                function sub_goods(){
                    var num = $('.num_show').val()
                    if(parseInt(num)>1){
                        var new_num = parseInt(num) - 1
                        $('.num_show').val(new_num)
                        var price = $('#ddf1').text()
                        var new_total = new_num * price
                        $('.total em').text(new_total+'元')
                    }
                }
                </script>
			</div>
			<div class="total">总价：<em>{{ goods.shop_price }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart"
                   id="add_cart"
                   onclick="add_cart({{ goods.id }});">
                    加入购物车
                </a>
			</div>


            {% csrf_token %}
            <script>
                function add_cart(id){
                    var num = $('.num_show').val()
                    var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                    $.ajax({
                        url:'/cart/add_cart/',
                        type:'POST',
                        data:{'goods_id':id, 'goods_num':num},
                        headers:{'X-CSRFToken': csrf},
                        dataType:'json',
                        success:function(data){
                            if(data.code == '200'){
                                $('#show_count').text(data.count)
                            }
                        },
                        error:function(data){
                            alert('失败')
                        }
                    })
                }

            </script>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for good in new_goods %}
                    <li>
						<a href="{% url 'goods:detail' good.id %}"><img src="/media/{{ good.goods_front_image }}"></a>
						<h4><a href="{% url 'goods:detail' good.id %}">{{ good.name }}</a></h4>
						<div class="prize">￥{{ good.shop_price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods.goods_desc | safe }}</dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock %}

{% block js2 %}
	<div class="add_jump"></div>

	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
					    <!--window.location.reload()-->
					});
			});
		})
	</script>
{% endblock %}

blog/fresh_shop/templates/index.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜-首页
{% endblock %}

{% block js1 %}
    {{ block.super }}
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock %}

{% block content %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href=""><img src="/static/images/adv01.jpg"></a>
			<a href=""><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>
    {% for data in result %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ data.0.category_type }}">
                {% for type in category_type %}
                    {% if type.0 == data.0.category_type%}
                        {{ type.1 }}
                    {% endif %}
                {% endfor %}
            </h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for i in data.1 %}
				<a href="{% url 'goods:detail' i.id %}">{{ i.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'goods:list' data.0.category_type %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/media/{{ data.0.category_front_image }}"></div>
			<ul class="goods_list fl">
             {% for i in data.1 %}
				<li>
					<h4><a href="{% url 'goods:detail' i.id %}">{{ i.name }}</a></h4>
					<a href="{% url 'goods:detail' i.id %}"><img src="/media/{{ i.goods_front_image }}"></a>
					<div class="prize">{{ i.shop_price }}</div>
				</li>
             {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}

{% endblock %}

{% block js2 %}
	<script type="text/javascript" src="/static/js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

blog/fresh_shop/templates/list.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜-商品列表
{% endblock %}

{% block content %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="{% url 'goods:list' 1 %}" class="fruit">新鲜水果</a></li>
					<li><a href="{% url 'goods:list' 2 %}" class="seafood">海鲜水产</a></li>
					<li><a href="{% url 'goods:list' 3 %}" class="meet">猪牛羊肉</a></li>
					<li><a href="{% url 'goods:list' 4 %}" class="egg">禽类蛋品</a></li>
					<li><a href="{% url 'goods:list' 5 %}" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="{% url 'goods:list' 6 %}" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="">全部分类</a>
		<span>></span>
		<a href="">
            {% for type in category_type %}
                {% if type.0 == id %}
                        {{ type.1 }}
                {% endif %}
            {% endfor %}
        </a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for good in new_goods %}
					<li>
						<a href="{% url 'goods:detail' good.id %}"><img src="/media/{{ good.goods_front_image }}"></a>
						<h4><a href="{% url 'goods:detail' good.id %}">{{ good.name }}</a></h4>
						<div class="prize">￥{{ good.shop_price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for goods in all_goods %}
				<li>
					<a href="{% url 'goods:detail' goods.id %}"><img src="/media/{{ goods.goods_front_image }}"></a>
					<h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goods.shop_price }}</span>
						<span class="unit">{{ goods.shop_price }}/500g</span>
						<a href="{% url 'goods:detail' goods.id %}" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if all_goods.has_previous %}
				<a href="{% url 'goods:list' id %}?page={{ all_goods.previous_page_number }}">上一页</a>
                {% endif %}
                {% for i in all_goods.paginator.page_range %}
				<a href="{% url 'goods:list' id %}?page={{ i }}" class="active">{{ i }}</a>
                {% endfor %}
                {% if all_goods.has_next %}
				<a href="{% url 'goods:list' id %}?page={{ all_goods.next_page_number }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>

{% endblock %}

blog/fresh_shop/templates/login.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜-登录
{% endblock %}

{% block js1 %}
{% endblock %}

{% block header %}
{% endblock %}

{% block search %}
{% endblock %}

{% block content %}
	<div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error" style="display:block;">{{ errors.username }}</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error" style="display:block;">{{ errors.pwd }}</div>
						<div class="more_input clearfix"></div>
						<input type="submit" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

blog/fresh_shop/templates/search.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜-搜索
{% endblock %}

{% block content %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="{% url 'goods:list' 1 %}" class="fruit">新鲜水果</a></li>
					<li><a href="{% url 'goods:list' 2 %}" class="seafood">海鲜水产</a></li>
					<li><a href="{% url 'goods:list' 3 %}" class="meet">猪牛羊肉</a></li>
					<li><a href="{% url 'goods:list' 4 %}" class="egg">禽类蛋品</a></li>
					<li><a href="{% url 'goods:list' 5 %}" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="{% url 'goods:list' 6 %}" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="">全部分类</a>
		<span>></span>
		<a href="">搜索</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
                <p>嘻嘻 不开放</p>
                {% comment %}
				<ul>
                    {% for good in new_goods %}
					<li>
						<a href=""><img src=""></a>
						<h4><a href="">{{ good.name }}</a></h4>
						<div class="prize">￥{{ good.shop_price }}</div>
					</li>
                    {% endfor %}
				</ul>
                {% endcomment %}
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
			</div>
			<ul class="goods_type_list clearfix">
				{% for good in goods %}
				<li>
					<a href="{% url 'goods:detail' good.id %}"><img src="/media/{{ good.goods_front_image }}"></a>
					<h4><a href="{% url 'goods:detail' good.id %}">{{ good.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ good.shop_price }}</span>
						<span class="unit">{{ good.shop_price }}/500g</span>
						<a href="{% url 'goods:detail' good.id %}" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>
			{% comment %}
			<div class="pagenation">
                {% if goods.has_previous %}
				<a href="{% url 'goods:search' id %}?page={{ goods.previous_page_number }}">上一页</a>
                {% endif %}
                {% for i in goods.paginator.page_range %}
				<a href="{% url 'goods:search' id %}?page={{ i }}" class="active">{{ i }}</a>
                {% endfor %}
                {% if goods.has_next %}
				<a href="{% url 'goods:search' id %}?page={{ goods.next_page_number }}">下一页></a>
                {% endif %}
			</div>
			{% endcomment %}
		</div>
	</div>
{% endblock %}